# Forgejo Actions CI
name: ci

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - native
          - macos-aarch64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: check
        run: |
          nix develop ./kicad-base -c just check --show-diff-on-failure
